name: Rest Test Deploy

on:
  push:
    branches: [ "main"]
env:
  amd64: rest_x64
  arm64: rest_arm
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Official SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2.3.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_SERVER }}

    - name: build
      run: |
        echo "test and build"
        git clean -df
        go test -parallel 4  github.com/zhaojunlucky/rest-test/pkg/core
        go test -parallel 4  github.com/zhaojunlucky/rest-test/pkg/model
        echo "build linux ${amd64}"
        env GOOS=linux GOARCH=amd64 go build -ldflags -o -o ${{env.amd64}} "-X main.Version=1.0.${{github.run_number}}" cmd/rest-test/rest.go
        
        echo "build darwin ${arm64}"
        env GOOS=darwin GOARCH=arm64 go build -ldflags -o -o ${{env.arm64}} "-X main.Version=1.0.${{github.run_number}}" cmd/rest-test/rest.go
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        path: |
          ${{env.amd64}}
          ${{env.arm64}}