name: Rest Test Deploy

on:
  push:
    branches: [ "main"]
env:
  amd64: rest_x64
  arm64: rest_arm
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Official SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2.3.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_SERVER }}

    - name: build
      run: |
        echo "test and build"
        go test -parallel 4  github.com/zhaojunlucky/rest-test/pkg/core
        go test -parallel 4  github.com/zhaojunlucky/rest-test/pkg/model
        echo "build linux ${amd64}"
        env GOOS=linux GOARCH=amd64 go build -ldflags "-X main.Version=1.0.${{github.run_number}}" -o ${{env.amd64}} cmd/rest-test/rest.go
        
        echo "build darwin ${arm64}"
        env GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.Version=1.0.${{github.run_number}}" -o ${{env.arm64}} cmd/rest-test/rest.go

    - name: publish release
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: |
        zip -r rest-test-1.0.${{github.run_number}}.zip ${{env.amd64}} ${{env.arm64}}
        gh release create v1.0.${{github.run_number}} -t v1.0.${{github.run_number}} --draft=false ./rest-test-1.0.${{github.run_number}}.zip